// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your tables here
    }
    Views: {
      // Add your views here
    }
    Functions: {
      // Add your functions here
    }
    Enums: {
      // Add your enums here
    }
    CompositeTypes: {
      // Add your composite types here
    }
  }
}

// Project reference: ca78ccef-7abc-4a23-8dfc-58572cc9d5fa
// Last updated: 2026-04-06T06:21:12.948219
